# Generated by Django 5.1 on 2025-07-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MathQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=100)),
                ("correct_answer", models.IntegerField()),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("addition", "Addition"),
                            ("subtraction", "Subtraction"),
                            ("multiplication", "Multiplication"),
                            ("division", "Division"),
                            ("pemdas", "PEMDAS"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
